name: Release on Merge

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - prod

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set Git Identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Build
        run: ./gradlew build

      - name: Tag and Push on Merge to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: |
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"
          # Additional release steps can be added here if needed

      - name: Tag and Push on PR to Production
        if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.base_ref == 'prod'
        run: |
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"
          # Additional release steps can be added here if needed

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/libs/*  # Adjust the path to your artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
