name: Release on Merge

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - prod

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set Git Identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Build (conditional execution based on event)
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: ./gradlew build

      - name: Store Run Number
        id: store_run_number
        run: echo "RUN_NUMBER=$(echo ${{ github.run_number }})" >> $GITHUB_ENV

      - name: Tag and Push on Merge to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: |
          git tag -a "v${{ env.RUN_NUMBER }}" -m "Release v${{ env.RUN_NUMBER }}"
          git push origin "v${{ env.RUN_NUMBER }}"

      - name: Tag and Push on PR to Production
        if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.base_ref == 'prod'
        run: |
          git tag -a "v${{ env.RUN_NUMBER }}" -m "Release v${{ env.RUN_NUMBER }}"
          git push origin "v${{ env.RUN_NUMBER }}"

      - name: Generate Release Notes
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        id: generate_release_notes
        uses: release-drafter/release-drafter@v5
        with:
          config-path: .github/release-drafter.yml  # Adjust the path as needed
          version: "v${{ env.RUN_NUMBER }}"
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release (conditional execution based on event)
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/libs/*  # Adjust the path to your artifacts
          tag_name: "v${{ env.RUN_NUMBER }}"  # Ensure a tag is associated with the release
          body: ${{ steps.generate_release_notes.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.22-7/x64
          JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.22-7/x64
          RUN_NUMBER: ${{ github.run_number }}
